backend:
  name: github
  repo: realankitt/bhandari-smile-design  # ← your actual GitHub repo
  branch: main
  auth_scope: repo

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title",        name: "title",      widget: "string"   }
      - { label: "Publish Date", name: "date",       widget: "datetime" }
      - { label: "Author",       name: "author",     widget: "string"   }
      - { label: "Hero Image",   name: "hero_image", widget: "image"    }
      - { label: "Body",         name: "body",       widget: "markdown" }
