backend:
  name: github
  repo: realankitt/bhandari-smile-design   # ← change this
  branch: main
  auth_scope: repo

media_folder: "public/uploads"  # where uploaded files go in your repo
public_folder: "/uploads"       # how they're referenced in your site

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/posts"     # where your markdown files live
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title",        name: "title",        widget: "string" }
      - { label: "Publish Date", name: "date",         widget: "datetime" }
      - { label: "Author",       name: "author",       widget: "string" }
      - { label: "Hero Image",   name: "hero_image",   widget: "image" }
      - { label: "Body",         name: "body",         widget: "markdown" }
